version: 1.0.{build}
image: Visual Studio 2019

build_script:
- ps: >-
    nuget restore .\Money.sln
    
    msbuild /p:Configuration=Release tools\DataGenerator\DataGenerator.csproj
    
    tools\DataGenerator\bin\Release\Lsquared.GenerateData.exe
    
    Move-Item -Path .\data.json.zip -Destination .\src\Money\ -Force
    
    dotnet restore .\src\Money\Money.csproj
    
    dotnet restore .\src\Money\Money.csproj
    
    dotnet build --no-restore -c Release .\src\Money\Money.csproj

test_script:
- ps: >-
    dotnet restore .\tests\Money.UnitTests\Money.UnitTests.csproj
    
    dotnet test --no-restore --collect "Code Coverage" -c Release .\tests\Money.UnitTests\Money.UnitTests.csproj

artifacts:
- path: .\*.nupkg

before_deploy:
- ps: dotnet pack --no-restore --no-build --include-symbols -o . -c Release .\src\Money\Money.csproj

deploy:
- provider: NuGet
  api_key:
    secure: baP1EKFns7P4lsmSh8d3avOmkW00zEzJX+2xTx9593RQagLkmQ3n25V2XvlTlJGI
  skip_symbols: false
  
