version: 1.0.{build}
image: Visual Studio 2019

init:
- ps: git config --global core.autocrlf true

before_build:
- ps: dotnet --version

build_script:
- ps: nuget restore .\Money.sln
- ps: msbuild /p:Configuration=Release tools\DataGenerator\DataGenerator.csproj
- ps: tools\DataGenerator\bin\Release\Lsquared.GenerateData.exe
- ps: Move-Item -Path .\data.json.zip -Destination .\src\Money\ -Force
- ps: dotnet restore .\src\Money\Money.csproj
- ps: dotnet restore .\src\Money\Money.csproj
- ps: dotnet build --no-restore -c Release .\src\Money\Money.csproj

test_script:
- ps: dotnet restore .\tests\Money.UnitTests\Money.UnitTests.csproj
- ps: dotnet test --no-restore --collect "Code Coverage" -c Release .\tests\Money.UnitTests\Money.UnitTests.csproj

after_test:
- ps: dotnet pack --no-restore --no-build --include-symbols -o . -c Release .\src\Money\Money.csproj

artifacts:
- path: .\*.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: baP1EKFns7P4lsmSh8d3avOmkW00zEzJX+2xTx9593RQagLkmQ3n25V2XvlTlJGI
  skip_symbols: false
  
