language: csharp
mono:
  - latest
solution: Money.sln
before_install:
    - mkdir .nuget
    - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/v3.5.0/NuGet.exe
install:
    - mono .nuget/nuget.exe restore Money.sln
script:
    - xbuild /p:Configuration=Release Money.sln
