language: csharp
mono: latest
dotnet: 2.1.502

solution: Money.sln

addons:
    apt:
        sources:
            #- sourceline: 'deb http://download.mono-project.com/repo/debian wheezy main'
            - sourceline: 'deb http://download.mono-project.com/repo/debian beta main'
        packages:
            - mono-devel
            #- mono-complete

install:
- dotnet restore Money.sln
script:
- xbuild /p:Configuration=Release tools/DataGenerator/DataGenerator.csproj
- mono tools/DataGenerator/bin/Release/Lsquared.GenerateData.exe
- mv -f data.json.zip src/Money/
- dotnet build --no-restore -c Release src/Money/Money.csproj
- dotnet test --no-restore --collect "Code Coverage" -c Release tests/Money.UnitTests/Money.UnitTests.csproj
