language: csharp
mono:
  - latest
solution: Money.sln
addons:
    apt:
        sources:
            - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
            #- sourceline: 'deb http://download.mono-project.com/repo/debian wheezy main'
            - sourceline: 'deb http://download.mono-project.com/repo/debian beta main'
        packages:
            - mono-devel
            - mono-complete
            - referenceassemblies-pcl
            - dotnet-dev-1.0.0-preview2-1-003177
before_install:
    - mkdir .nuget
    - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/v3.5.0/NuGet.exe
script:
    - xbuild /p:Configuration=Release Money.sln
